name: List episodes

on:
  workflow_dispatch:
  schedule:
    - cron: "05 6 * * FRI" # Run every Friday at 7:05 CET/GMT+1
  push:

jobs:
  refresh:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: make import-rss
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
